name: Maven Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-maven:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: create Settings.xml
        uses: s4u/maven-settings-action@v2.8.0
        with:
          servers: |
            [{
              "id": "github",
              "username": "smartjigar",
              "password": ${{ secrets.GITHUB_TOKEN }}
            }]
          profiles: |
            [{
            "profile":{
                  "id":"",
                  "repositories":{
                      "repository":{
                        "id":"github",
                        "url":"https://maven.pkg.github.com/Cofinity-X/cofinity-x-keycloak-auth",
                        "snapshots":{
                            "enabled":"true"
                          }
                      }          
                  }
              }
            }]

      - name: Publish package
        run: mvn --batch-mode -DuseGitHubPackages=true deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}