name: Maven Deploy
on:
  push:
    branches:
      - master

jobs:
  deploy-maven:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Publish package
        run: mvn --batch-mode -s ./.github/workflows/maven-settings.xml deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}